project:
  type: website
  output-dir: docs

website:
  title: "Timelines"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - proposal.qmd
      - Deconvolution.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

